### ISSUE TITLE
Is Signatures a relevant use case?

### ISSUE THREAD

**Issue by ioggstream** [martinthomson/http-request-date#1]
## Question

The considerations in this document make me think that Signature is not a relevant use case,
at least to be mentioned in the Introduction.

While similar considerations apply to any timestamp conveyed by protocols not designed for time synchronization,
that is JWT header parameters, or Signature field parameters like `created` and `expires`,
these are better suited to convey time information related to the validity of signatures  than the `Date` header.

The same considerations will probably apply wrt avoiding replay attacks.

**Comment by martinthomson** [comment]
Hey Roberto, I've made a few changes to the document to address this specific issue; is that the version you are looking at?

See https://martinthomson.github.io/http-request-date/draft-thomson-httpapi-date-requests.html for the latest (unpublished) version.

**Comment by ioggstream** [comment]
Martin, thanks for the changes: they go in the right direction. I will share some feedback on the anti-reply part.
